queue_rules:
  - name: default
    conditions:
      - label=ci:mergify
    
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - check-success=trivial
      - check-success=minor
      - label=ci:mergify
    actions:
      queue:
        name: default
        require_branch_protection: true
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: