name: create-issue
on:
  pull_request:
#    types: [labeled, synchronize]
    types: [labeled]
      

jobs:
  make-issue:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:issue'))

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: dump context
        run: |
          cat << OBJECT
          ${{ toJson(github.event) }}
          OBJECT
      - name: callout PR user
        run: echo ${{ github.event.pull_request.user.login }}
      - name: create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
        with:
          assignees: ${{ github.event.pull_request.user.login }}
          filename: .github/ci-error-template.md