name: Binary Size Log Test

on:
  workflow_dispatch: {}

# uncomment this section to run on schedule
#  schedule:
#    # 6am or 7am PT depending on daylight savings
#    - cron: '0 13 * * *'

# uncomment this section to run on a tag
#  pull_request:
#    types: [labeled]
#    branches:
#      - main


jobs:
  binary-size-log:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci:test')) ||
      github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@v3
      with:
        repository: jwithers/citests
        fetch-depth: 0
    - name: test checkout
      run: |
        ls -alh
        git branch -al
        git checkout -b log_test origin/log_test
        git status
        echo `date` >> delete/tempfile
        git commit -a -m "automated tempfile update"
        git push
